name: Build EXE with PyInstaller

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller SofiaApp.py --onefile --hidden-import encodings

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SofiaApp
        path: dist/SofiaApp.exe
